dist: xenial
language: c++
os: linux
compiler:
  - g++


python:
 - 3.6

before_install:
 #- apt-get install python3.6
 #- sudo apt-get install python3-dev
 - sudo apt-get -y install python3-pip python-dev
 - pip install --upgrade pip
 - python3 -V
 - pip3 -V
 - sudo apt-get install g++-mingw-w64-i686
 - which python
 - echo $PYTHONHOME
 - echo $PYTHONPATH
 #- export PYTHON=$PYTHONPATH;
 #- echo $PYTHON
 - sudo apt install qt5-default


script:
 - qmake Test_Python.pro
 - make
