dist: trusty
language: c++
os: linux
compiler: 
 - g++
  
virtualenv : 
  system_site_packages :  true

before_install:
 - sudo apt-get -y install python3-pip python3-dev
 - pip install --upgrade pip
 #- python3 -V
 #- pip3 -V
 - sudo apt-get install g++-mingw-w64-i686
 #- which python
 - echo $PYTHONPATH:$(pwd)
 - echo $PYTHONHOME
 - echo $PYTHONPATH
 #- export PYTHON=$PYTHONPATH
 #- echo $PYTHON
 - sudo apt install qt5-default
#

script:
 - qmake Test_Python.pro
 - make
